update_room_temperature:

read_modbus_register:
  fields:
    register_address:
      required: true
      example: 1000
      selector:
        number:
          min: 0
          max: 65535
          mode: box

write_modbus_register:
  fields:
    register_address:
      required: true
      example: 1000
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    value:
      required: true
      example: 100
      selector:
        number:
          min: -32768
          max: 65535
          mode: box
